name: testtest2
favicon: null
layout_spectrum: 0.8286566457245499
typography_spectrum: 0.5611339353490621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3425371409393847
  lightness: 0.957609090488404
  saturation: 0.5469581172801554
  rhythmicContrast: 0.7952738751191646
purpose: []
